### ISSUE TITLE
"Header" as header text isn't handled correctly

### ISSUE THREAD

**Issue by RobinLe1402** [tanabe/markdown-live-preview#25]
When using "Header" as a header, as in `# Header`, this header gets shown at the top of the site and the actual output window ignores it.

**Comment by mehul-srivastava** [comment]
The problem behind this is that markdown converts `# Header` to `<h1 id="header">Header</h1>`. There is a style in the CSS file which also uses the same ID as a result it applies styles to that particular line. I have made a PR to fix it.

**Comment by tanabe** [comment]
@mehul-srivastava 
Thank you for your contribution.
I investigated the cause of the problem.
I think this bug would be caused by marked.js's behaviour. (see the [reference](https://marked.js.org/using_advanced#options))
marked.js replaces id attributes automatically when some input has occured.
So, I'm going to update marked.js and I will disable feature that replacing id attributes.
